email: candicewilliams2511@gmail.com

sass:
    sass_dir: _sass

collections:
  courses:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

baseurl: /
url: https://candicewilliams.github.io

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true